import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import NavComponent from "@/components/NavComponent";

const josefinSans = Josefin_Sans({
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.className} antialiased`}
      >
        <div className='bg-black min-h-[100vh]'>
          <div className='max-w-7xl mx-auto'>
            <header className='py-4'>
              <NavComponent />
            </header>
            {children}
            <footer className='text-xs lg:text-sm text-center text-white/45 py-10'>
              <p>Copyright &copy; {new Date().getFullYear()} All rights reserved | This website was made by Cromax</p>
            </footer>
          </div>
          {/* <ScrollToTop /> */}
        </div>
      </body>
    </html>
  );
}
